### ISSUE TITLE
Naming of models' class attributes

### ISSUE THREAD

**Issue by nlahaye** [gugarosa/learnergy#2] opened 2021-06-15 02:52 UTC
The variable names used in the getters and setters of each model class are different than what is initialized in the constructor.

<img width="441" alt="Screen Shot 2021-06-14 at 7 37 42 PM" src="https://user-images.githubusercontent.com/13157468/121985030-d92ee280-cd48-11eb-8929-4c39fd378ee8.png">

Note that the name 'W' is used in __init__, but '_W' is used as the variable name in the getters and setters, both of which have the same name as the variable initialized in __init__  'W'. This issue is the same for all member variables. I have tested the DBN and GaussianVarianceRBM subclasses as well, and it looks like the issue persists across all other subclasses.

<img width="376" alt="Screen Shot 2021-06-14 at 7 38 32 PM" src="https://user-images.githubusercontent.com/13157468/121985026-d8964c00-cd48-11eb-9acb-02507d063aed.png">

 - OS: CentOS 7.8
 - Virtual Environment  conda 4.10.1
 - Python Version 3.8

This causes issues when trying to make copies of classes for things like multi-GPU training via  torch.nn.DistributedDataParallel

**Comment by gugarosa** [comment] 2021-06-15 13:05
Hello Nick! I hope everything is going well with you.

Actually, this is the intended Python pattern when implementing both getters and setters using the property decorator.

Could you please send me the real error when performing copies using `torch.nn.DistributedDataParallel`?

Thank you and best regards,
Gustavo.

**Comment by nlahaye** [comment] 2021-06-16 08:13
Hi Gustavo! I hope all is well with you also! Thank you for/great work writing this library! It is a huge help to finally have PyTorch-friendly  RBMs/DBNs.  

Here is a quick example that produces the error I was running into in my code:

```
import os
from datetime import timedelta

import torch.cuda
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP

from learnergy.models.gaussian import VarianceGaussianRBM

def setup_ddp(rank, world_size, device_ids, use_gpu=True):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'
    os.environ['CUDA_VISIBLE_DEVICES'] = ",".join([str(i) for i in device_ids])
    os.environ['NCCL_SOCKET_IFNAME'] = "lo"

    driver = "nccl"
    if not use_gpu or not torch.cuda.is_available():
        driver = "gloo"

    # initialize the process group
    dist.init_process_group(driver, rank=rank, world_size=world_size, init_method="env://", timeout=timedelta(seconds=10))

def cleanup_ddp():
    dist.destroy_process_group()



device_ids = [0,1,2]

setup_ddp(0, 1, device_ids)

# Creates a VarianceGaussianRBM-based class
model = VarianceGaussianRBM(n_visible=784, n_hidden=128, steps=1, learning_rate=0.1,
                            momentum=0, decay=0, temperature=1, use_gpu=True)

ddp_model = DDP(model, device_ids=device_ids).cuda()

cleanup_ddp()
```

I end up getting this error:

> 2021-06-16 01:10:02,265 - learnergy.utils.exception — ERROR — TypeError: `W` should be a PyTorch parameter.
> Traceback (most recent call last):
>   File "test_DDP.py", line 36, in <module>
>     ddp_model = DDP(model, device_ids=device_ids).cuda()
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 448, in __init__
>     self._ddp_init_helper()
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 503, in _ddp_init_helper
>     self._module_copies = replicate(self.module, self.device_ids, detach=True)
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 148, in replicate
>     setattr(replica, key, param)
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 995, in __setattr__
>     object.__setattr__(self, name, value)
>   File "/usr/local/anaconda3/lib/python3.8/site-packages/learnergy/models/bernoulli/rbm.py", line 225, in W
>     raise e.TypeError('`W` should be a PyTorch parameter')
> learnergy.utils.exception.TypeError


I made some edits to a local copy of the library to get it to cooperate with `torch.nn.DistributedDataParallel`, but I wanted to make sure a long term solution was in line with your design choices, etc. 

These type of errors continue to pop up until all of the parameters, optimizers, and models naming conventions change. 

Please let me know if there's anything else I can do to help!

Nick

**Comment by gugarosa** [comment] 2021-06-16 13:48
Hello Nick! I really appreciate that Learnergy is helping you out!

Thanks a lot for the source code and the prompted error, I can almost fully understand what is happenning now. I will take a few days to solve it because we are out of GPUs in our lab, so I am not able to test it out and check the exact issue.

Nevertheless, from what I am seeing, the main problem lies on the type-checking function inside the setter, for example (https://github.com/gugarosa/learnergy/blob/master/learnergy/models/bernoulli/rbm.py#L225):

```
if not isinstance(W, nn.Parameter):
  raise e.TypeError('`W` should be a PyTorch parameter')
```

My initial guess is that the `DistributedDataParallel` class wraps the model and eventually changes its parameters to a type that is different than `nn.Parameter`, probably a `Variable` / `Tensor` or something like that. I took a look over the PyTorch docs and could find a `Reducer` class (https://github.com/pytorch/pytorch/blob/v1.9.0/torch/lib/c10d/reducer.hpp#L58) that is applied when using `DistributedDataParallel` (https://github.com/pytorch/pytorch/blob/v1.7.0/torch/nn/parallel/distributed.py#L525).

There is one thing that I would like you to test, if it is possible, please. Instead of changing the naming conventions, just delete the `raise e.TypeError` lines, please. I am pretty hopeful that it will solve the problem and thus, a straightforward fix to the library.

Thank you and best regards,
Gustavo.

**Comment by nlahaye** [comment] 2021-06-16 17:14
Hi Gustavo,
   That's correct, they get passed in as `Tensor` types. I  think I tried that and it causes issues when setting up the optimizer, because `nn.Parameter` types automatically get added to the parameter set, but I may have missed something because I am not as familiar with the code.
   
Thank you for your help, and no worries on timing!

Nick

**Comment by gugarosa** [comment] 2021-07-12 13:28
Hello Nick! I hope everything is going well with you.

Sorry for taking too long, but I just managed to grab a GPU and test out what is going on. Nevertheless, I could not reproduce the same error (PyTorch 1.7.1 and CUDA 10.1).

Could you also please provide both PyTorch and CUDA versions that you were using?

PS: A possible cause might be that I do only have one GPU and thus had to change `device_ids` to `[0]`.

Thank you and best regards,
Gustavo.

**Comment by nlahaye** [comment] 2021-07-14 07:12
Hi Gustavo! Thanks, you as well!

That is correct. I just verified this issue only occurs if multiple devices are within the device_ids list.

**Comment by nlahaye** [comment] 2021-07-14 07:14
Sorry I forgot to add this info:

CUDA v11.3
PyTorch v1.8.1

Thanks! 
Nick

**Comment by gugarosa** [comment] 2021-07-19 18:10
Sweet Nick, thank you so much! I will gather a machine with multiple GPUs and test it out!

Best regards,
Gustavo.

**Comment by nlahaye** [comment] 2021-10-05 16:55
Hello Gustavo,
    I hope all is well! I wanted to check in and see if there was any updates on this?
    
    Thanks!
    Nick

**Comment by gugarosa** [comment] 2021-11-10 12:28
Hi @nlahaye! Sorry for the late response, but I still have not been able to properly test on a multi-gpu environment.

Nevertheless, from our previous conversations, the problem would be fixed by just removing the type checking on the parameters properties, correct?

If so, would you please kindly submit a PR with those changes? We barely use these checks as the parameters are always defined within the classes; thus I would say that multi-gpu compatibility is better than type checking these variables.

Best regards,
Gustavo.

**Comment by nlahaye** [comment] 2021-12-14 02:20
Hi @gugarosa. Ok, I will go ahead and do that within the week. Thanks!

Nick

**Comment by gugarosa** [comment] 2021-12-14 11:38
No worries, take your time! Thanks a lot Nick!!

Best regards,
Gustavo.

**Comment by nlahaye** [comment] 2022-01-06 01:02
Happy New Year, Gustavo! I hope you are doing well!

I went ahead and updated and issued a pull request. 

Please let me know if anything else is needed or if you have any questions.

Thanks!
Nick

**Comment by gugarosa** [comment] 2022-04-04 18:18
Just merged it! Thanks so much Nick and sorry for this taking out more time than we imagined!

Best regards,
Gustavo.

**Closed by gugarosa** 2022-04-04 18:18 UTC
Labels: bug
